const moment = require('moment')
moment.locale('id')

exports.getFormat1 = e => moment(e, 'D MMMM YYYY').format('YYYYMMDD')
exports.getFormat2 = e => moment(e, 'D MMMM YYYY').format('YYYY-MM-DD')
exports.getFormat3 = tgl => tgl.format('YYYY-MM-DD')
exports.getFormat4 = tgl => tgl.format('D-M-YYYY')
exports.getFormat5 = tgl => tgl.format('dddd, D-M-YYYY')
exports.getFormat6 = tgl => tgl.format('DD-MM-YYYY')
exports.getHari = e => moment( e, 'e').format('dddd').join(', ')
exports.getHariBy = tgl => tgl.format('dddd')
exports.getHariSekarang = () => moment().format('dddd')
exports.getJam = e => moment(e, 'x').format('H')
exports.getJamBy = tgl => tgl.format('H')
exports.getLongFormat = s => moment(s * 1e3).format('LLLL')
exports.getTahunBy = e => moment(e, 'YYYY-MM-DD').format('YYYY')
exports.getTahun = () => moment().format('YYYY')
exports.getTglBesok = () => moment().add(1, 'd')
exports.getTglBesokBy = tgl => tgl.add(1, 'd')
exports.getTglDaftar = e => moment(e, 'x').format('DD-MM-YYYY')
exports.getTglDaftarHariIni = () => moment().format('DD-MM-YYYY')
exports.getTglHariIni = () => moment()
exports.getTglLahir = e => moment(e).format('dddd, LL')
exports.getTglLusa = () => moment().add(2, 'd')
exports.getTglLusaBy = tgl => tgl.add(2, 'd')
exports.getUmur = tgl =>  moment(tgl).fromNow().split(' ').slice(0, 2).join(' ')
exports.getUmurArr = e => moment(e).fromNow().split(' ').slice(0, 2)
exports.isMinggu = tgl => moment(tgl).weekday() === 0
